version: "3"
services:
  golang:
    image: registry.cn-hangzhou.aliyuncs.com/qiuapeng/golang
    container_name: golang
    ports:
      - "80:8080"
    networks:
      - default

networks:
  default: