version: "3"
services:
  golang:
    image: registry.cn-hangzhou.aliyuncs.com/qiuapeng/golang:VERSION
    container_name: golang
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default