version: "3"
services:
  golang:
    image: registry.cn-hangzhou.aliyuncs.com/qiuapeng921/golang:VERSION
    container_name: golang
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default: